// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5E1ePB8r1zVNcZdMTZWYt7Z9wF27PEo4',
    appId: '1:774209121154:web:aca3f1332ef0416ba63d9b',
    messagingSenderId: '774209121154',
    projectId: 'notesapp-firebasedb-crud',
    authDomain: 'notesapp-firebasedb-crud.firebaseapp.com',
    storageBucket: 'notesapp-firebasedb-crud.firebasestorage.app',
    measurementId: 'G-L2ML4HV00C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNS3CNxDGLmvX8swnqexT9pYOHCsg6UNg',
    appId: '1:774209121154:android:dba11e3a8cd77d37a63d9b',
    messagingSenderId: '774209121154',
    projectId: 'notesapp-firebasedb-crud',
    storageBucket: 'notesapp-firebasedb-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCffuXlg-WyMCo9POlzwoXmV1GR-fOIWK0',
    appId: '1:774209121154:ios:d1ef1dc9af216c9fa63d9b',
    messagingSenderId: '774209121154',
    projectId: 'notesapp-firebasedb-crud',
    storageBucket: 'notesapp-firebasedb-crud.firebasestorage.app',
    iosBundleId: 'com.example.firebasedbCrudNotesFlutterApp',
  );
}
